import { getAllPosts } from '$lib/content.js';
import { siteConfig } from '$lib/config.js';
import { getPostImageUrl } from '$lib/seo.js';
import { xmlCdata, xmlText } from '$lib/xml.js';
import { compileMarkdownToHtml } from '$lib/rss-content.ts';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { RequestHandler } from './$types.js';

export const prerender = true;

function getMimeType(filePath: string): string {
	const ext = path.extname(filePath).toLowerCase();
	switch (ext) {
		case '.png':
			return 'image/png';
		case '.jpg':
		case '.jpeg':
			return 'image/jpeg';
		case '.webp':
			return 'image/webp';
		case '.gif':
			return 'image/gif';
		case '.avif':
			return 'image/avif';
		default:
			return 'application/octet-stream';
	}
}

async function getEnclosureLength(filePath: string): Promise<string | null> {
	try {
		const fullPath = path.join(process.cwd(), filePath);
		const stat = await fs.stat(fullPath);
		return stat.size.toString();
	} catch {
		return null;
	}
}

function truncateDescription(text: string, length = 160): string {
	if (text.length <= length) return text;
	const lastSpace = text.lastIndexOf(' ', length);
	return lastSpace > 0 ? text.slice(0, lastSpace) + '…' : text.slice(0, length) + '…';
}

export const GET: RequestHandler = async () => {
	const posts = await getAllPosts();
	const lastBuildDate = new Date().toUTCString();

	const items = await Promise.all(
		posts.slice(0, siteConfig.rssLimit ?? 20).map(async (post) => {
			const imageUrl = getPostImageUrl(post, siteConfig.url);
			let enclosure = '';

			// If it's a dynamic og image, we skip enclosure.
			if (post.cover) {
				// The cover is an absolute url to a static asset imported during build (e.g., /_app/immutable/assets/cover.X.jpg)
				// Or the original path if it didn't get hashed yet. Let's trace it back to original file in writings.
				// Wait, post.cover is generated by imageModules which gives the Vite built path or the dev path.
				// However, if we just parse the original file from the post directory, we can use `fs.stat`.
				// Since we don't know the exact resolved path of Vite easily inside server code if it's hashed,
				// we can just check the original path which we can predict.
				// Wait! post.cover could be the original url in dev, or hashed in prod.
				// But we know it came from `/writings/${post.slug}/cover.*`.
				const possibleExts = ['avif', 'webp', 'png', 'jpg', 'jpeg'];
				let length: string | null = null;
				let type = 'image/png';

				for (const ext of possibleExts) {
					const testPath = `writings/${post.slug}/cover.${ext}`;
					length = await getEnclosureLength(testPath);
					if (length) {
						type = getMimeType(testPath);
						break;
					}
				}

				if (length) {
					enclosure = `\n      <enclosure url="${xmlText(imageUrl)}" length="${length}" type="${type}" />`;
				}
			}

			const contentHtml = await compileMarkdownToHtml(post.body);
			// Reformat category to not alter case, use post tags directly
			const categories = post.tags
				.map((tag) => `\n      <category>${xmlCdata(tag)}</category>`)
				.join('');

			// Generate 120-180 char description
			const safeDesc = truncateDescription(post.plainText || post.description, 160);

			return `
    <item>
      <title>${xmlCdata(post.title)}</title>
      <description>${xmlCdata(safeDesc)}</description>
      <link>${xmlText(`${siteConfig.url}/${post.slug}`)}</link>
      <guid isPermaLink="true">${xmlText(`${siteConfig.url}/${post.slug}`)}</guid>
      <pubDate>${new Date(post.publishedAt).toUTCString()}</pubDate>${enclosure}
      <author>${xmlText(`dummy@example.com (${siteConfig.author})`)}</author>
      <dc:creator>${xmlCdata(siteConfig.author)}</dc:creator>${categories}
      <content:encoded>${xmlCdata(contentHtml)}</content:encoded>
    </item>`;
		})
	);

	const itemsXml = items.join('');
	const logoUrl = `${siteConfig.url}/og.png`;

	const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>${xmlCdata(siteConfig.title)}</title>
    <description>${xmlCdata(siteConfig.description)}</description>
    <link>${xmlText(siteConfig.url)}</link>
    <atom:link href="${xmlText(`${siteConfig.url}/rss.xml`)}" rel="self" type="application/rss+xml"/>
    <language>en-us</language>
    <lastBuildDate>${lastBuildDate}</lastBuildDate>
    <generator>SvelteKit</generator>
    <docs>https://www.rssboard.org/rss-specification</docs>
    <ttl>60</ttl>
    <copyright>${xmlText(`© ${new Date().getFullYear().toString()} ${siteConfig.author}`)}</copyright>
    <managingEditor>${xmlText(`dummy@example.com (${siteConfig.author})`)}</managingEditor>
    <webMaster>${xmlText(`dummy@example.com (${siteConfig.author})`)}</webMaster>
    <image>
      <url>${xmlText(logoUrl)}</url>
      <title>${xmlCdata(siteConfig.title)}</title>
      <link>${xmlText(siteConfig.url)}</link>
      <width>1200</width>
      <height>630</height>
    </image>
    ${itemsXml}
  </channel>
</rss>`;

	return new Response(rss.trim(), {
		headers: {
			'Content-Type': 'application/xml; charset=utf-8',
			'Cache-Control': 'max-age=0, s-maxage=3600',
		},
	});
};
